//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STARS.Applications.VETS.Plugins.VTS.Interface.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("STARS.Applications.VETS.Plugins.VTS.Interface.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomFieldValues.
        /// </summary>
        internal static string CustomFieldValues {
            get {
                return ResourceManager.GetString("CustomFieldValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntityUris.VETSTEST.Test.
        /// </summary>
        internal static string EntityUriVetsTest {
            get {
                return ResourceManager.GetString("EntityUriVetsTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STARS.Applications.VETS.Execution.
        /// </summary>
        internal static string ExecutionSource {
            get {
                return ResourceManager.GetString("ExecutionSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuels.
        /// </summary>
        internal static string Fuels {
            get {
                return ResourceManager.GetString("Fuels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test {0} is starting run sequence.
        /// </summary>
        internal static string ImportedTestIsStarting {
            get {
                return ResourceManager.GetString("ImportedTestIsStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported test {0} cannot be started at this time.
        /// </summary>
        internal static string ImpotedTestCannotStart {
            get {
                return ResourceManager.GetString("ImpotedTestCannotStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SamplingConfiguration.
        /// </summary>
        internal static string SamplingConfiguration {
            get {
                return ResourceManager.GetString("SamplingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test {0} has been imported.
        /// </summary>
        internal static string TestImportFinished {
            get {
                return ResourceManager.GetString("TestImportFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The import of test {0} has started.
        /// </summary>
        internal static string TestImportStarted {
            get {
                return ResourceManager.GetString("TestImportStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The import of the test list has finished.
        /// </summary>
        internal static string TestListImportFinished {
            get {
                return ResourceManager.GetString("TestListImportFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The import of the test list has started.
        /// </summary>
        internal static string TestListImportStarted {
            get {
                return ResourceManager.GetString("TestListImportStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests.
        /// </summary>
        internal static string Tests {
            get {
                return ResourceManager.GetString("Tests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicles.
        /// </summary>
        internal static string Vehicles {
            get {
                return ResourceManager.GetString("Vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] xmlTemplate {
            get {
                object obj = ResourceManager.GetObject("xmlTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
